ign-rviz-plugins/CMakeLists.txt
ign-rviz-plugins/ign-rviz-plugins.xml
ign-rviz-plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign-rviz-plugins/include/ignition/rviz/plugins/tf_display.hpp
ign-rviz/include/ignition/rviz/rviz.hpp

Fixes to compile the code
Signed-off-by: ahcorde <ahcorde@gmail.com>

Fixes to compile the code

---

README.md
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_common/include/ignition/rviz/common/frame_manager.hpp
ign_rviz_common/src/rviz/common/frame_manager.cpp
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/tf_display.hpp
ign_rviz_plugins/src/rviz/plugins/tf_display.cpp

Add code documentation

---

ign_rviz/CMakeLists.txt
ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz/package.xml
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/ign_rviz_plugins.xml
ign_rviz_plugins/include/ignition/rviz/plugins/laser_scan_display.hpp
ign_rviz_plugins/package.xml
ign_rviz_plugins/src/rviz/plugins/laser_scan_display.cpp

* Create laser scan visualization plugin for ign-rviz
* Add laser scan display option in custom drawer menu in the main application
Reference to issue #17

Add LaserScan visualization plugin

---

ign_rviz_plugins/src/rviz/plugins/tf_display.cpp

Fix arrow and axis visual rendering

---

ign_rviz_plugins/src/rviz/plugins/laser_scan_display.cpp

Fix point geometry insertion error

---

ign_rviz_plugins/include/ignition/rviz/plugins/tf_display.qml
ign_rviz_plugins/src/rviz/plugins/laser_scan_display.cpp
ign_rviz_plugins/src/rviz/plugins/tf_display.cpp

Added a cardItem to the plugin GUI

Feature gui config

---

ign_rviz/include/ignition/rviz/RVizDrawer.qml

Update custom drawer menu actions to work with Ubuntu 20.04

Update custom drawer menu

---

.gitignore
ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz/src/rviz/rviz.cpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/AxesDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/AxesDisplay.qml
ign_rviz_plugins/include/ignition/rviz/plugins/AxesDisplay.qrc
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/src/rviz/plugins/AxesDisplay.cpp

Axes visualization plugin with gui config using ign-gui plugins.
GUI Config options:
- Set axis frame
- Set length
- Set radius
- Set axis arrow head visibility

Axes visualization plugin

---

ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_common/include/ignition/rviz/common/frame_manager.hpp
ign_rviz_common/src/rviz/common/frame_manager.cpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/TFDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/TFDisplay.qml
ign_rviz_plugins/src/rviz/plugins/TFDisplay.cpp

TF visualization plugin config

---

ign_rviz/package.xml
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/package.xml

Remove pluginlib dependency

---

README.md
ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/ImageDisplay.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/ImageDisplay.qml
ign_rviz_plugins/src/rviz/plugins/ImageDisplay.cpp

I have also written two scripts to publish images in `bgr8`, `rgb8` and `mono8` format from webcam and video file. 
This can be found [here](https://gist.github.com/Sarath18/7c48b6f2e667bf6dab1b12f419cab397).

Add Image Display plugin

---

ign_rviz_plugins/include/ignition/rviz/plugins/LaserScanDisplay.hpp
ign_rviz_plugins/res/qml/LaserScanDisplay.qml
ign_rviz_plugins/src/rviz/plugins/LaserScanDisplay.cpp

Use LidarVisual to visualize LaserScan data

---

docker/Dockerfile
ign_rviz_common/include/ignition/rviz/common/frame_manager.hpp
ign_rviz_common/src/rviz/common/frame_manager.cpp
ign_rviz_plugins/include/ignition/rviz/plugins/AxesDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/GlobalOptions.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/ImageDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/LaserScanDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/TFDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/src/rviz/plugins/AxesDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/ImageDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/LaserScanDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/TFDisplay.cpp

Refactor code and update documentation

---

ign_rviz_plugins/include/ignition/rviz/plugins/ImageDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/LaserScanDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/ImageDisplay.qml
ign_rviz_plugins/res/qml/LaserScanDisplay.qml
ign_rviz_plugins/res/qml/QoSConfig.qml
ign_rviz_plugins/src/rviz/plugins/ImageDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/LaserScanDisplay.cpp

* Add QoS config qml
* Add QoS settings in base class
* Add QoS config to LaserScan and ImageDisplay plugins

Add QoS settings to display plugins

---

ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/PointStampedDisplay.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/PointStampedDisplay.qml
ign_rviz_plugins/src/rviz/plugins/PointStampedDisplay.cpp

Render `geometry_msgs/msg/PointStamped` data received on ROS2 topics

Add PointStamped display plugin

---

ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/PoseDisplay.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/PoseDisplay.qml
ign_rviz_plugins/src/rviz/plugins/PoseDisplay.cpp

Render geometry_msgs/msg/PoseStamped data received on ROS2 topics
The sample test script can be found [here](https://gist.github.com/Sarath18/c25ebd015ca4bf4793150f94387c7a2f#file-posepublisher-py).

Add Pose display plugin

---

ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/PolygonDisplay.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/PolygonDisplay.qml
ign_rviz_plugins/src/rviz/plugins/PolygonDisplay.cpp

Render `geometry_msgs/msg/PolygonStamped` data received on ROS2 topics.
The sample test script can be found [here](https://gist.github.com/Sarath18/c25ebd015ca4bf4793150f94387c7a2f#file-polygonpublisher-py).

Add Polygon display plugin

---

ign_rviz_plugins/CMakeLists.txt

Reference to issue #44 
I have also added a macro `add_ign_rviz_plugin` to simplify adding new plugins.

Refactor CMakeLists.txt

---

ign_rviz_plugins/include/ignition/rviz/plugins/PoseDisplay.hpp
ign_rviz_plugins/res/qml/PoseDisplay.qml
ign_rviz_plugins/src/rviz/plugins/PoseDisplay.cpp

Fix spelling in Pose display plugin
﻿Signed-off-by: Sarathkrishnan Ramesh <sarathkrishnan99@gmail.com>

Fix spelling

---

README.md
ign_rviz/CMakeLists.txt
ign_rviz/package.xml
ign_rviz_common/package.xml
ign_rviz_plugins/package.xml
ign_rviz_plugins/src/rviz/plugins/LaserScanDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/PathDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/PointStampedDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/PolygonDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/PoseArrayDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/PoseDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/RobotModelDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/TFDisplay.cpp

Just a few suggestions:
* Add some links to the README
* Remove some dependencies / headers where they weren't being used
* Added Ignition libraries to `package.xml` so they're found on colcon workspace

Suggestions to README and others

---

README.md

Add link to wiki in README.md

---

ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz/src/rviz/rviz.cpp
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerManager.hpp
ign_rviz_plugins/res/Plugins.qrc
ign_rviz_plugins/res/qml/MarkerDisplay.qml
ign_rviz_plugins/src/rviz/plugins/MarkerDisplay.cpp
ign_rviz_plugins/src/rviz/plugins/MarkerManager.cpp

Part 1 of #60
- Create a Marker manager class to process and visualize the incoming marker messages
- Add, Delete and Delete All marker actions
- Basic Geometries (Arrow, Cube, Sphere, Cylinder)
- Geometry List (Line List, Line Strip, Points, Triangle List)
- Basic marker properties (Color, Scale, and Pose)

Add Marker display plugin

---

ign_rviz/CMakeLists.txt
ign_rviz/include/ignition/rviz/RVizDrawer.qml
ign_rviz/package.xml
ign_rviz/src/rviz/rviz.cpp
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerManager.hpp
ign_rviz_plugins/package.xml
ign_rviz_plugins/src/rviz/plugins/MarkerManager.cpp
ign_rviz_plugins/src/rviz/plugins/RobotModelDisplay.cpp

Part 2 of #60
Add support for the following geometry types:
- Sphere List
- Cube List
- Text markers
- Mesh markers

Add support for more Marker geometry types

---

.github/workflows/ci.yml

Signed-off-by: ahcorde <ahcorde@gmail.com>
I created a `galactic` branch, CI should compile the code with `Edifice` and `Galactic`
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

[Galactic] Clean up CI

---

.github/workflows/ci.yml
README.md
ign_rviz/CMakeLists.txt
ign_rviz/include/ignition/rviz/rviz.hpp
ign_rviz/package.xml
ign_rviz/src/rviz/application.cpp
ign_rviz/src/rviz/rviz.cpp
ign_rviz_common/CMakeLists.txt
ign_rviz_common/include/ignition/rviz/common/frame_manager.hpp
ign_rviz_common/package.xml
ign_rviz_plugins/CMakeLists.txt
ign_rviz_plugins/include/ignition/rviz/plugins/GPSDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/ImageDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/LaserScanDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerArrayDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/MarkerManager.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/PathDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/PointStampedDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/PolygonDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/PoseArrayDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/PoseDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/RobotModelDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/TFDisplay.hpp
ign_rviz_plugins/include/ignition/rviz/plugins/message_display_base.hpp
ign_rviz_plugins/package.xml
ign_rviz_plugins/src/rviz/plugins/MarkerManager.cpp
ign_rviz_plugins/src/rviz/plugins/RobotModelDisplay.cpp

Fixed CI on main
Rolling (a.k.a. Humble) should work with `Fortress` and `Rolling`
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

Fixed CI on main
